- name: Configure and deploy PostgreSQL DB
  hosts: db_host
  become: yes
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL and dependencies
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3
          - python3-pip
          - python3-psycopg2
        state: present

    - name: Copy pg_hba.conf to DB host
      ansible.builtin.copy:
        src: ./pg_hba.conf
        dest: /etc/postgresql/15/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Copy config-postgresql to DB host
      ansible.builtin.copy:
        src: ./config-postgresql
        dest: /etc/postgresql/15/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: "Add bot access to pg_hba.conf"
      ansible.builtin.lineinfile:
        line: "host all all {{ hostvars['bot'].ansible_host }}/24 password"
        path: /etc/postgresql/15/main/pg_hba.conf

    - name: "Add replication access to pg_hba.conf"
      ansible.builtin.lineinfile:
        line: "host replication repl_user {{ hostvars['db_repl'].ansible_host }}/24 scram-sha-256"
        path: /etc/postgresql/15/main/pg_hba.conf

    - name: Restart PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: Refresh collation version on template1
      become: true
      become_user: postgres
      command: psql -c "ALTER DATABASE template1 REFRESH COLLATION VERSION;"

    - name: "Create bot_db database"
      become_user: postgres
      postgresql_db:
        name: "bot_db"
        state: present

    - name: "Create phone_number table"
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: |
          CREATE TABLE IF NOT EXISTS phone_number (
            Number_ID SERIAL PRIMARY KEY,
            Phone_Number VARCHAR(255) NOT NULL
          );

    - name: "Create email table"
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: |
          CREATE TABLE IF NOT EXISTS email (
            Email_ID SERIAL PRIMARY KEY,
            Email_Address VARCHAR(255) NOT NULL
          );

    - name: "Grant privileges on phone_number table"
      become: true
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: "GRANT ALL PRIVILEGES ON TABLE phone_number TO postgres;"

    - name: "Grant privileges on email table"
      become: true
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: "GRANT ALL PRIVILEGES ON TABLE email TO postgres;"

    - name: Create database and replication user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: repl_user
        password: "{{ lookup('file', './pgpass') }}"
        role_attr_flags: "REPLICATION"
        state: present

- name: Configure and deploy PostgreSQL replica
  hosts: db_repl_host
  become: yes
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL and dependencies
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3
          - python3-pip
        state: present

    - name: Update postgresql.conf for replication
      become: true
      ansible.builtin.lineinfile:
        path: /etc/postgresql/15/main/postgresql.conf
        regexp: '^#?(listen_addresses) ='
        line: "listen_addresses = 'localhost, {{ hostvars['db_repl'].ansible_host }}'"

    - name: Stop PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: stopped

    - name: Remove files from main directory
      ansible.builtin.file:
        path: /var/lib/postgresql/15/main
        state: absent

    - name: Create main directory
      ansible.builtin.file:
        path: /var/lib/postgresql/15/main
        state: directory
        owner: postgres
        group: postgres
        mode: '0700'

    - name: Perform base backup from Master server
      become: true
      ansible.builtin.command:
        cmd: pg_basebackup -R -h {{ hostvars['db'].ansible_host }} -U repl_user -D /var/lib/postgresql/15/main
        creates: /var/lib/postgresql/15/main/PG_VERSION
      environment:
        PGPASSWORD: "{{ lookup('file', './pgpass') }}"

    - name: Start PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: started

- name: Deploy Telegram Bot
  hosts: bot_host
  become: yes
  vars:
    bot_repo: "https://github.com/johnnysvill/DevOps.git"
    bot_directory: "/opt/telegram_bot"
    bot_venv_directory: "{{ bot_directory }}/venv"
    bot_python: "/usr/bin/python3"
    bot_subdirectory: "bot"

  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - python3
          - python3-venv
          - python3-pip
          - git
        state: present

    - name: Create bot directory
      ansible.builtin.file:
        path: "{{ bot_directory }}"
        state: directory
        mode: '0755'

    - name: Clone bot repository
      ansible.builtin.git:
        repo: "{{ bot_repo }}"
        dest: "{{ bot_directory }}"
        version: "docker"
        force: yes
        accept_hostkey: yes

    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: "{{ bot_python }} -m venv {{ bot_venv_directory }}"
        creates: "{{ bot_venv_directory }}"

    - name: Install Python dependencies
      ansible.builtin.pip:
        requirements: "{{ bot_directory }}/{{ bot_subdirectory }}/requirements.txt"
        virtualenv: "{{ bot_venv_directory }}"

    - name: Copy environment variables file
      ansible.builtin.copy:
        src: "./.env"
        dest: "{{ bot_directory }}/.env"
        mode: '0600'

    - name: Start bot
      ansible.builtin.command:
        cmd: "{{ bot_venv_directory }}/bin/python {{ bot_directory }}/bot/bot.py &"
        chdir: "{{ bot_directory }}"
