- name: Configure and deploy PostgreSQL DB
  hosts: db_host
  become: yes
  tasks:
    - name: Update APT cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install PostgreSQL and dependencies
      ansible.builtin.apt:
        name:
          - postgresql
          - postgresql-contrib
          - python3
          - python3-pip
        state: present

    - name: "pip_psycorg2"
      pip:
        state: present
        name:
          - psycopg2

    - name: Copy pg_hba.conf to DB host
      ansible.builtin.copy:
        src: ./pg_hba.conf
        dest: /etc/postgresql/15/main/pg_hba.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: Copy config-postgresql to DB host
      ansible.builtin.copy:
        src: ./config-postgresql
        dest: /etc/postgresql/15/main/postgresql.conf
        owner: postgres
        group: postgres
        mode: '0644'

    - name: "Add bot access to pg_hba.conf"
      ansible.builtin.lineinfile:
        line: "host all all {{ hostvars['bot_host'].ansible_host }}/24 password"
        path: /etc/postgresql/15/main/pg_hba.conf

    - name: "Add replication access to pg_hba.conf"
      ansible.builtin.lineinfile:
        line: "host replication repl_user {{ hostvars['db_repl_host'].ansible_host }}/24 scram-sha-256"
        path: /etc/postgresql/15/main/pg_hba.conf

    - name: Restart PostgreSQL service
      ansible.builtin.service:
        name: postgresql
        state: restarted

    - name: "Create bot_db database"
      become_user: postgres
      become: yes
      postgresql_db:
        name: "bot_db"
        state: present

    - name: "Create phone_number table"
      become: yes
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: |
          CREATE TABLE IF NOT EXISTS phone_number (
            Number_ID SERIAL PRIMARY KEY,
            Phone_Number VARCHAR(255) NOT NULL
          );

    - name: "Create email table"
      become: yes
      become_user: postgres
      postgresql_query:
        db: "bot_db"
        query: |
          CREATE TABLE IF NOT EXISTS email (
            Email_ID SERIAL PRIMARY KEY,
            Email_Address VARCHAR(255) NOT NULL
          );

    - name: "Create a database user"
      become_user: postgres
      become: yes
      postgresql_user:
        name: "postgres"
        password: "1"
        state: present

    - name: "Grant privileges to the user on the database"
      become_user: postgres
      become: yes
      postgresql_privs:
        db: "bot_db"
        roles: "postgres"
        privs: "ALL"
        state: present

    - name: Create database and replication user
      become_user: postgres
      community.postgresql.postgresql_user:
        name: repl_user
        password: "{{ lookup('file', './pgpass') }}"
        priv: "REPLICATION"
